export const SET_USER_NAME = 'SET_USER_NAME';
export const GET_USER_NAME = 'GET_USER_NAME';
export const UPDATE_CORRECT_ANSWERS = 'UPDATE_CORRECT_ANSWERS';
export const UPDATE_WRONG_ANSWERS = 'UPDATE_WRONG_ANSWERS';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
