export const GET_USER = 'GET_USER';
export const SET_USER_NAME = 'SET_USER_NAME';
export const INCREMENT_CORRECT_ANSWERS = 'INCREMENT_CORRECT_ANSWERS';
export const INCREMENT_WRONG_ANSWERS = 'INCREMENT_WRONG_ANSWERS';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
